s3:
  trg_bucket: 'adaptivesharks-test-etl-target'
  access_key_name: 'aws_access_key'
  secret_access_key_name: 'aws_secret_access_key'
  s3_region: 'us-west-1'
polygon:
  polygon_key: 'polygon_api_key'
source:
  src_input_date: '2024-05-30'
  src_input_date_format: '%Y-%m-%d'
  src_tickers:
    [
      'AAPL'
    ]
  src_columns:
    [
      'open',
      'high',
      'low',
      'close',
      'volume',
      'vwap',
      'timestamp',
      'transaction',
      'ticker'
    ]
  src_col_ticker: 'ticker'
  src_col_timestamp: 'timestamp'
  src_col_open: 'open'
  src_col_high: 'high'
  src_col_low: 'low'
  src_col_close: 'close'
  src_col_volume: 'volume'
  src_col_vwap: 'vwap'
  src_col_otc: 'otc'
  src_col_transaction: 'transaction'
target:
  trg_prefix: 'daily/'
  trg_key_date_format: '%Y%m%d'
  trg_format: 'parquet'
  trg_columns:
    [
      'stock_ticker',
      'date_time',
      'opening_price',
      'closing_price',
      'low_price',
      'high_price',
      'traded_volume',
      'daily_return',
      'daily_volatility',
      'intraday_range'
    ]
  trg_col_open: 'opening_price'
  trg_col_close: 'closing_price'
  trg_col_low: 'low_price'
  trg_col_high: 'high_price'
  trg_col_volume: 'traded_volume'
  trg_col_return: 'daily_return'
  trg_col_volatility: 'daily_volatility'
  trg_col_intraday_range: 'intraday_range'
  trg_col_datetime: 'date_time'
  trg_col_ticker: 'stock_ticker'
  trg_dtypes:
    stock_ticker: 'object'
    date_time: 'datetime64[ns]'
    opening_price: 'float64'
    closing_price: 'float64'
    low_price: 'float64'
    high_price: 'float64'
    traded_volume: 'int64'
    daily_return: 'float64'
    daily_volatility: 'float64'
    intraday_range: 'float64'

logging:
  version: 1
  formatters:
    polygon:
      format: "Polygon Transformer [%(asctime)s] %(levelname)s: %(name)s [Line: %(lineno)d]: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: polygon
      level: INFO
  root:
    level: INFO
    handlers: [console]